13th spring - 1st iteration
Semenem29/java-shareit pull request #1
Opened 2023-12-19 11:37 UTC by Semenem29

creating the skeleton of the App

2023-12-19 18:55 UTC, Yang-Pi requested changes

2023-12-19 18:55 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Этот комментарий можно уже удалить

2023-12-19 18:55 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") Long ownerId, @RequestBody ItemDto itemDto) {
Все-таки рекомендую сделать валдиацию на уровне модели, потому что сейчас нужно применить довольно примитивные проверки вроде "непустое поле", и отсечь такой неверный запрос на уровне контроллера будет идеально, потому что методы сервиса даже не будут вызваны

2023-12-19 18:55 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (text.isBlank()) {
Я бы и такой вариант не разрешал и приравнял бы его к null

2023-12-19 18:55 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.getAllUsers().stream()
Лучше все же и такое преобразование спрятать в сервис, как это реализовано для Item

2023-12-20 09:00 UTC, Semenem29 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
удалил все TODO add-controllers

2023-12-20 09:06 UTC, Semenem29 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.getAllUsers().stream()
done

2023-12-20 10:06 UTC, Semenem29 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (text.isBlank()) {
я бы тоже, но в этом случае валится тест в постман, который ожидает статус код 200. 
![image](https://github.com/Semenem29/java-shareit/assets/127120548/8e7b1696-0e07-4862-8b98-6df50f98ce24)

2023-12-20 13:18 UTC, Semenem29 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") Long ownerId, @RequestBody ItemDto itemDto) {
Сделал, проверь, пожалуйста, и дай обратную связь. 
Не нашел в интернете консолидированную информацию, где было бы исчерпывающе описаны инструкции. Например, здесь - https://www.baeldung.com/spring-valid-vs-validated инфа для новичка далеко не полная.

2023-12-20 21:15 UTC, Yang-Pi approved these changes

2023-12-20 21:18 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Validated(Create.class)
Ты смешал несколько вариантов - Validated и Valid
https://stackoverflow.com/questions/36173332/difference-between-valid-and-validated-in-spring

Valid без груп будет достаточно

2024-02-17 19:28 UTC, merged